apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: postgres
        command:
          - sh
          - -c
          - echo "starting db migration"
