apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: default
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: migration
              image: postgres
              command:
                - sh
                - -c
                - echo "starting db migration"
