apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres
  namespace: default
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers: 
            - name: postgres
              image: postgres
              imagePullPolicy: Always
          restartPolicy: OnFailure
      ttlSecondsAfterFinished: 172800

